name: recent_roll_drawer
description: A Flutter package providing a unique roll drawer with screen previews and customizable animations.
version: 1.0.0
homepage: https://github.com/AdeelWajid/recent_roll_drawer
repository: https://github.com/AdeelWajid/recent_roll_drawer

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
